"""Business services package."""

from memexpert.services.auth_service import (
    ACCESS_TOKEN_TYPE,
    HS256_ALGORITHM,
    AuthService,
    AuthSession,
)
from memexpert.services.collection_service import CollectionService
from memexpert.services.errors import (
    AccountUnavailableError,
    AuthConfigurationError,
    AuthenticatedUserNotFoundError,
    AuthServiceError,
    CollectionNotFoundError,
    CollectionServiceError,
    CollectionWriteAccessError,
    DuplicateCollectionInviteError,
    DuplicateFavoritesCollectionError,
    DuplicateIdentityError,
    EmailAlreadyInUseError,
    ExpiredTokenError,
    GuestCollectionAccessError,
    InvalidCollectionInviteError,
    InvalidCollectionMembershipError,
    InvalidCollectionTitleError,
    InvalidCredentialsError,
    InvalidIdentityError,
    InvalidTokenError,
    MissingTokenError,
    ProviderAccessDeniedError,
    ProviderNotConfiguredError,
    ProviderPayloadExpiredError,
    ProviderPayloadInvalidError,
    RefreshTokenReuseError,
    ServiceError,
    ServiceValidationError,
    UpgradeRequiredError,
    UserNotFoundError,
    UserServiceError,
    UserStateMismatchError,
)
from memexpert.services.provider_auth_service import ProviderAuthService
from memexpert.services.user_service import DEFAULT_GUEST_LIFETIME, FAVORITES_TITLE, UserService

__all__ = [
    "ACCESS_TOKEN_TYPE",
    "AccountUnavailableError",
    "AuthenticatedUserNotFoundError",
    "AuthConfigurationError",
    "AuthService",
    "AuthServiceError",
    "AuthSession",
    "CollectionNotFoundError",
    "CollectionService",
    "CollectionServiceError",
    "CollectionWriteAccessError",
    "DEFAULT_GUEST_LIFETIME",
    "DuplicateCollectionInviteError",
    "DuplicateFavoritesCollectionError",
    "DuplicateIdentityError",
    "EmailAlreadyInUseError",
    "ExpiredTokenError",
    "FAVORITES_TITLE",
    "GuestCollectionAccessError",
    "HS256_ALGORITHM",
    "InvalidCollectionInviteError",
    "InvalidCollectionMembershipError",
    "InvalidCollectionTitleError",
    "InvalidCredentialsError",
    "InvalidIdentityError",
    "InvalidTokenError",
    "MissingTokenError",
    "ProviderAccessDeniedError",
    "ProviderAuthService",
    "ProviderNotConfiguredError",
    "ProviderPayloadExpiredError",
    "ProviderPayloadInvalidError",
    "RefreshTokenReuseError",
    "ServiceError",
    "ServiceValidationError",
    "UpgradeRequiredError",
    "UserNotFoundError",
    "UserService",
    "UserServiceError",
    "UserStateMismatchError",
]
