# ruff: noqa: E501,I001,TC003
"""initial schema"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_deletion_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('deletion_requested', 'grace_period_expired', 'hard_deleted', 'cancelled', name='accountdeletionaction', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_deletion_logs'))
    )
    op.create_index('ix_account_deletion_logs_user_id_created_at', 'account_deletion_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('account_merge_logs',
    sa.Column('guest_account_id', sa.Uuid(), nullable=False),
    sa.Column('target_account_id', sa.Uuid(), nullable=False),
    sa.Column('favorites_transferred', sa.Integer(), nullable=False),
    sa.Column('views_transferred', sa.Integer(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_merge_logs'))
    )
    op.create_index('ix_account_merge_logs_target_account_id_created_at', 'account_merge_logs', ['target_account_id', 'created_at'], unique=False)
    op.create_table('meme_templates',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_curated', sa.Boolean(), nullable=False),
    sa.Column('base_image_url', sa.Text(), nullable=True),
    sa.Column('text_regions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meme_templates'))
    )
    op.create_index('ix_meme_templates_is_curated', 'meme_templates', ['is_curated'], unique=False)
    op.create_index('uq_meme_templates_slug', 'meme_templates', ['slug'], unique=True)
    op.create_table('source_channels',
    sa.Column('platform', sa.Enum('reddit', 'telegram', 'vk', name='sourceplatform', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('platform_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_read_post_id', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_channels')),
    sa.UniqueConstraint('platform', 'platform_id', name='uq_source_channels_platform_platform_id')
    )
    op.create_index('ix_source_channels_is_active_platform', 'source_channels', ['is_active', 'platform'], unique=False)
    op.create_table('users',
    sa.Column('account_type', sa.Enum('guest', 'full', name='accounttype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'deletion_pending', 'deleted', name='accountstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('active_save_collection_id', sa.Uuid(), nullable=True),
    sa.Column('nsfw_enabled', sa.Boolean(), nullable=False),
    sa.Column('language', sa.Enum('any', 'en', 'ru', name='userlanguage', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('guest_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletion_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletion_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('email IS NULL OR email = lower(email)', name=op.f('ck_users_users_email_lowercase')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('ix_users_account_type_status', 'users', ['account_type', 'status'], unique=False)
    op.create_index('uq_users_email_not_null', 'users', ['email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_index('uq_users_google_id_not_null', 'users', ['google_id'], unique=True, postgresql_where=sa.text('google_id IS NOT NULL'))
    op.create_index('uq_users_telegram_id_not_null', 'users', ['telegram_id'], unique=True, postgresql_where=sa.text('telegram_id IS NOT NULL'))
    op.create_table('analytics_events',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('click', 'favorite', 'impression', 'inline_query', 'meme_like', 'meme_save', 'meme_send', 'meme_view', 'save', 'search_query', 'share', 'view', name='analyticseventtype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_analytics_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_events'))
    )
    op.create_index('ix_analytics_events_event_type_occurred_at', 'analytics_events', ['event_type', 'occurred_at'], unique=False)
    op.create_index('ix_analytics_events_user_id_occurred_at', 'analytics_events', ['user_id', 'occurred_at'], unique=False)
    op.create_table('channel_suggestions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('reddit', 'telegram', 'vk', name='sourceplatform', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('channel_url', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('approved', 'pending', 'rejected', name='channelsuggestionstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_channel_suggestions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_suggestions'))
    )
    op.create_index('ix_channel_suggestions_status_created_at', 'channel_suggestions', ['status', 'created_at'], unique=False)
    op.create_table('collections',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.Enum('custom', 'favorites', name='collectionkind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'unlisted', 'public', name='collectionvisibility', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(trim(title)) > 0', name=op.f('ck_collections_collections_title_not_blank')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_collections_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections'))
    )
    op.create_index('ix_collections_owner_id_updated_at', 'collections', ['owner_id', 'updated_at'], unique=False)
    op.create_index('uq_collections_one_favorites_per_owner', 'collections', ['owner_id'], unique=True, postgresql_where=sa.text("kind = 'favorites'"))
    op.create_foreign_key(
        op.f('fk_users_active_save_collection_id_collections'),
        'users',
        'collections',
        ['active_save_collection_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_table('inline_usage_events',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('group_hash', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_inline_usage_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inline_usage_events'))
    )
    op.create_index('ix_inline_usage_events_group_hash_occurred_at', 'inline_usage_events', ['group_hash', 'occurred_at'], unique=False)
    op.create_index('ix_inline_usage_events_user_id_occurred_at', 'inline_usage_events', ['user_id', 'occurred_at'], unique=False)
    op.create_table('memes',
    sa.Column('media_type', sa.Enum('audio', 'gif', 'image', 'link', 'text', 'video', name='contentkind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('primary_file_id', sa.Uuid(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('language', sa.Enum('en', 'mixed', 'none', 'ru', name='contentlanguage', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('is_nsfw', sa.Boolean(), nullable=False),
    sa.Column('popularity_score', sa.Float(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name=op.f('fk_memes_author_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['meme_templates.id'], name=op.f('fk_memes_template_id_meme_templates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memes'))
    )
    op.create_index('ix_memes_author_user_id_created_at', 'memes', ['author_user_id', 'created_at'], unique=False)
    op.create_index('ix_memes_media_type_language', 'memes', ['media_type', 'language'], unique=False)
    op.create_index('ix_memes_visibility_popularity_created_at', 'memes', ['is_public', 'popularity_score', 'created_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index('ix_refresh_tokens_user_id_expires_at', 'refresh_tokens', ['user_id', 'expires_at'], unique=False)
    op.create_index('uq_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('collection_invites',
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='collectionmembershiprole', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('channel', sa.Enum('direct_link', 'email', 'telegram', name='collectioninvitechannel', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('accepted', 'expired', 'pending', 'revoked', name='collectioninvitestatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recipient_email', sa.String(length=320), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_uses IS NULL OR max_uses > 0', name=op.f('ck_collection_invites_collection_invites_max_uses_positive')),
    sa.CheckConstraint('use_count >= 0', name=op.f('ck_collection_invites_collection_invites_use_count_non_negative')),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_collection_invites_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_collection_invites_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_invites'))
    )
    op.create_index('ix_collection_invites_collection_id_status', 'collection_invites', ['collection_id', 'status'], unique=False)
    op.create_index('uq_collection_invites_token_hash', 'collection_invites', ['token_hash'], unique=True)
    op.create_table('collection_members',
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='collectionmembershiprole', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_collection_members_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_collection_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'user_id', name=op.f('pk_collection_members'))
    )
    op.create_index('ix_collection_members_user_id_role', 'collection_members', ['user_id', 'role'], unique=False)
    op.create_table('collection_memes',
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('meme_id', sa.Uuid(), nullable=False),
    sa.Column('added_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], name=op.f('fk_collection_memes_added_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_collection_memes_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meme_id'], ['memes.id'], name=op.f('fk_collection_memes_meme_id_memes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'meme_id', name=op.f('pk_collection_memes'))
    )
    op.create_index('ix_collection_memes_collection_added_at', 'collection_memes', ['collection_id', 'added_at', 'meme_id'], unique=False)
    op.create_table('meme_files',
    sa.Column('meme_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('failed', 'pending', 'processing', 'ready', name='contentprocessingstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('s3_original_key', sa.Text(), nullable=False),
    sa.Column('s3_web_video_key', sa.Text(), nullable=True),
    sa.Column('perceptual_hash', sa.String(length=64), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('blur_hash', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meme_id'], ['memes.id'], name=op.f('fk_meme_files_meme_id_memes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meme_files'))
    )
    op.create_index('ix_meme_files_meme_id_status', 'meme_files', ['meme_id', 'status'], unique=False)
    op.create_index('ix_meme_files_perceptual_hash', 'meme_files', ['perceptual_hash'], unique=False)
    op.create_index('uq_meme_files_single_primary_per_meme', 'meme_files', ['meme_id'], unique=True, postgresql_where=sa.text('is_primary'))
    op.create_foreign_key(
        op.f('fk_memes_primary_file_id_meme_files'),
        'memes',
        'meme_files',
        ['primary_file_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_table('meme_popularity_snapshots',
    sa.Column('meme_id', sa.Uuid(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_views', sa.Integer(), nullable=False),
    sa.Column('source_reactions', sa.Integer(), nullable=False),
    sa.Column('source_reposts', sa.Integer(), nullable=False),
    sa.Column('platform_views', sa.Integer(), nullable=False),
    sa.Column('platform_sends', sa.Integer(), nullable=False),
    sa.Column('platform_saves', sa.Integer(), nullable=False),
    sa.Column('platform_likes', sa.Integer(), nullable=False),
    sa.Column('popularity_score', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['meme_id'], ['memes.id'], name=op.f('fk_meme_popularity_snapshots_meme_id_memes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meme_popularity_snapshots')),
    sa.UniqueConstraint('meme_id', 'captured_at', name='uq_meme_popularity_snapshots_meme_id_captured_at')
    )
    op.create_index('ix_meme_popularity_snapshots_meme_id_captured_at', 'meme_popularity_snapshots', ['meme_id', 'captured_at'], unique=False)
    op.create_table('meme_seo_pages',
    sa.Column('meme_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('page_title', sa.String(length=255), nullable=False),
    sa.Column('meta_description', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meme_id'], ['memes.id'], name=op.f('fk_meme_seo_pages_meme_id_memes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meme_id', name=op.f('pk_meme_seo_pages'))
    )
    op.create_index('ix_meme_seo_pages_generated_at', 'meme_seo_pages', ['generated_at'], unique=False)
    op.create_index('uq_meme_seo_pages_slug', 'meme_seo_pages', ['slug'], unique=True)
    op.create_table('pinned_memes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('meme_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('position BETWEEN 1 AND 20', name=op.f('ck_pinned_memes_pinned_memes_position_range')),
    sa.ForeignKeyConstraint(['meme_id'], ['memes.id'], name=op.f('fk_pinned_memes_meme_id_memes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pinned_memes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'meme_id', name=op.f('pk_pinned_memes'))
    )
    op.create_index('uq_pinned_memes_user_id_position', 'pinned_memes', ['user_id', 'position'], unique=True)
    op.create_table('embedding_cache',
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('input_type', sa.Enum('image', 'text', name='embeddinginputtype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('embedding', postgresql.BYTEA(), nullable=False),
    sa.Column('model_version', sa.String(length=255), nullable=False),
    sa.Column('source_file_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['meme_files.id'], name=op.f('fk_embedding_cache_source_file_id_meme_files'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embedding_cache')),
    sa.UniqueConstraint('input_hash', 'model_version', 'input_type', name='uq_embedding_cache_input_hash_model_version_input_type')
    )
    op.create_index('ix_embedding_cache_source_file_id', 'embedding_cache', ['source_file_id'], unique=False)
    op.create_table('meme_sources',
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('reddit', 'telegram', 'vk', name='sourceplatform', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('post_id', sa.String(length=255), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('reactions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_first_source', sa.Boolean(), nullable=False),
    sa.Column('source_alive', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['meme_files.id'], name=op.f('fk_meme_sources_file_id_meme_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meme_sources')),
    sa.UniqueConstraint('platform', 'source_id', 'post_id', name='uq_meme_sources_platform_source_post')
    )
    op.create_index('ix_meme_sources_file_id_platform', 'meme_sources', ['file_id', 'platform'], unique=False)
    op.create_table('telegram_file_id_cache',
    sa.Column('meme_file_id', sa.Uuid(), nullable=False),
    sa.Column('bot_scope', sa.String(length=128), nullable=False),
    sa.Column('media_format', sa.Enum('animation', 'photo', name='telegrammediaformat', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('telegram_file_id', sa.Text(), nullable=False),
    sa.Column('telegram_file_unique_id', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meme_file_id'], ['meme_files.id'], name=op.f('fk_telegram_file_id_cache_meme_file_id_meme_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_file_id_cache'))
    )
    op.create_index('uq_telegram_file_id_cache_file_format_scope', 'telegram_file_id_cache', ['meme_file_id', 'media_format', 'bot_scope'], unique=True)
    # ### end Alembic commands ###



def downgrade() -> None:
    """Revert this revision."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_telegram_file_id_cache_file_format_scope', table_name='telegram_file_id_cache')
    op.drop_table('telegram_file_id_cache')
    op.drop_index('ix_meme_sources_file_id_platform', table_name='meme_sources')
    op.drop_table('meme_sources')
    op.drop_index('ix_embedding_cache_source_file_id', table_name='embedding_cache')
    op.drop_table('embedding_cache')
    op.drop_index('uq_pinned_memes_user_id_position', table_name='pinned_memes')
    op.drop_table('pinned_memes')
    op.drop_index('uq_meme_seo_pages_slug', table_name='meme_seo_pages')
    op.drop_index('ix_meme_seo_pages_generated_at', table_name='meme_seo_pages')
    op.drop_table('meme_seo_pages')
    op.drop_index('ix_meme_popularity_snapshots_meme_id_captured_at', table_name='meme_popularity_snapshots')
    op.drop_table('meme_popularity_snapshots')
    op.drop_constraint(op.f('fk_memes_primary_file_id_meme_files'), 'memes', type_='foreignkey')
    op.drop_index('uq_meme_files_single_primary_per_meme', table_name='meme_files', postgresql_where=sa.text('is_primary'))
    op.drop_index('ix_meme_files_perceptual_hash', table_name='meme_files')
    op.drop_index('ix_meme_files_meme_id_status', table_name='meme_files')
    op.drop_table('meme_files')
    op.drop_index('ix_collection_memes_collection_added_at', table_name='collection_memes')
    op.drop_table('collection_memes')
    op.drop_index('ix_collection_members_user_id_role', table_name='collection_members')
    op.drop_table('collection_members')
    op.drop_index('uq_collection_invites_token_hash', table_name='collection_invites')
    op.drop_index('ix_collection_invites_collection_id_status', table_name='collection_invites')
    op.drop_table('collection_invites')
    op.drop_index('uq_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_user_id_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_memes_visibility_popularity_created_at', table_name='memes')
    op.drop_index('ix_memes_media_type_language', table_name='memes')
    op.drop_index('ix_memes_author_user_id_created_at', table_name='memes')
    op.drop_table('memes')
    op.drop_index('ix_inline_usage_events_user_id_occurred_at', table_name='inline_usage_events')
    op.drop_index('ix_inline_usage_events_group_hash_occurred_at', table_name='inline_usage_events')
    op.drop_table('inline_usage_events')
    op.drop_constraint(op.f('fk_users_active_save_collection_id_collections'), 'users', type_='foreignkey')
    op.drop_index('uq_collections_one_favorites_per_owner', table_name='collections', postgresql_where=sa.text("kind = 'favorites'"))
    op.drop_index('ix_collections_owner_id_updated_at', table_name='collections')
    op.drop_table('collections')
    op.drop_index('ix_channel_suggestions_status_created_at', table_name='channel_suggestions')
    op.drop_table('channel_suggestions')
    op.drop_index('ix_analytics_events_user_id_occurred_at', table_name='analytics_events')
    op.drop_index('ix_analytics_events_event_type_occurred_at', table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index('uq_users_telegram_id_not_null', table_name='users', postgresql_where=sa.text('telegram_id IS NOT NULL'))
    op.drop_index('uq_users_google_id_not_null', table_name='users', postgresql_where=sa.text('google_id IS NOT NULL'))
    op.drop_index('uq_users_email_not_null', table_name='users', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_index('ix_users_account_type_status', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_source_channels_is_active_platform', table_name='source_channels')
    op.drop_table('source_channels')
    op.drop_index('uq_meme_templates_slug', table_name='meme_templates')
    op.drop_index('ix_meme_templates_is_curated', table_name='meme_templates')
    op.drop_table('meme_templates')
    op.drop_index('ix_account_merge_logs_target_account_id_created_at', table_name='account_merge_logs')
    op.drop_table('account_merge_logs')
    op.drop_index('ix_account_deletion_logs_user_id_created_at', table_name='account_deletion_logs')
    op.drop_table('account_deletion_logs')
    # ### end Alembic commands ###
