//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::memes::Entity as Memes;
pub use super::slug_redirects::Entity as SlugRedirects;
pub use super::tg_uses::Entity as TgUses;
pub use super::translations::Entity as Translations;
pub use super::web_visits::Entity as WebVisits;
