//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "translations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub meme_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub language: String,
    pub title: String,
    pub caption: String,
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::memes::Entity",
        from = "Column::MemeId",
        to = "super::memes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Memes,
}

impl Related<super::memes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Memes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
