"""Shared ORM metadata surface for services, tests, and Alembic."""

from memexpert.models.base import Base, TimestampMixin, UUIDPrimaryKeyMixin, utcnow
from memexpert.models.collection import Collection, CollectionInvite, CollectionMember, CollectionMeme, PinnedMeme
from memexpert.models.content import (
    EmbeddingCache,
    Meme,
    MemeFile,
    MemePopularitySnapshot,
    MemeSeoPage,
    MemeSource,
    MemeTemplate,
    SourceChannel,
    TelegramFileIdCache,
)
from memexpert.models.enums import (
    AccountDeletionAction,
    AccountStatus,
    AccountType,
    AnalyticsEventType,
    AuthProvider,
    ChannelSuggestionStatus,
    CollectionInviteChannel,
    CollectionInviteStatus,
    CollectionKind,
    CollectionMembershipRole,
    CollectionVisibility,
    ContentKind,
    ContentLanguage,
    ContentProcessingStatus,
    ContentSourceKind,
    EmbeddingInputType,
    SourcePlatform,
    TelegramMediaFormat,
    UserLanguage,
    string_enum,
)
from memexpert.models.user import (
    AccountDeletionLog,
    AccountMergeLog,
    AnalyticsEvent,
    ChannelSuggestion,
    InlineUsageEvent,
    RefreshToken,
    User,
)

metadata = Base.metadata

__all__ = [
    "AccountDeletionAction",
    "AccountDeletionLog",
    "AccountMergeLog",
    "AccountStatus",
    "AccountType",
    "AnalyticsEvent",
    "AnalyticsEventType",
    "AuthProvider",
    "Base",
    "ChannelSuggestion",
    "ChannelSuggestionStatus",
    "Collection",
    "CollectionInvite",
    "CollectionInviteChannel",
    "CollectionInviteStatus",
    "CollectionKind",
    "CollectionMember",
    "CollectionMembershipRole",
    "CollectionMeme",
    "CollectionVisibility",
    "ContentKind",
    "ContentLanguage",
    "ContentProcessingStatus",
    "ContentSourceKind",
    "EmbeddingCache",
    "EmbeddingInputType",
    "InlineUsageEvent",
    "Meme",
    "MemeFile",
    "MemePopularitySnapshot",
    "MemeSeoPage",
    "MemeSource",
    "MemeTemplate",
    "PinnedMeme",
    "RefreshToken",
    "SourceChannel",
    "SourcePlatform",
    "TelegramFileIdCache",
    "TelegramMediaFormat",
    "TimestampMixin",
    "UUIDPrimaryKeyMixin",
    "User",
    "UserLanguage",
    "metadata",
    "string_enum",
    "utcnow",
]
